### ISSUE TITLE
Unclear whether members can publicly discuss incidents

### ISSUE THREAD

**Issue by mjg59** [fantasylandinst/fcop#46] opened 2017-02-15 23:35 UTC
If resolution does not result in a member being expelled, any member (including any victims) publicly describing the incident may be considered to be shaming the member

**Comment by jdegoes** [comment] 2017-02-16 16:29
Indeed, explicitly publicly shaming a violator is prohibited because a consequence has already been imposed on the violator and therefore the victim is discouraged from imposing an additional one.

There are two possibilities:

1. The victim is satisfied with the consequence imposed by the arbiter on the violator, and believes the community leaders to be acting in good faith.
2. The victim is not satisfied with the consequence imposed by the arbiter, and believes the community leaders to be acting in bad faith.

In the first case, both cases, no shaming applies. 

However, in the second case, the community is judged corrupt by the victim, which means I would encourage the victim to expose the corruption publicly. FCOP protects against corrupt communities by preventing the FCOP community from taking any action against FCOP violations except banishment, and in the case of a corrupt community, banishment no longer becomes a punishment, because trust has been violated between members and leadership.

Something not stated that could be further elaborated is that in the event someone is banned by a corrupt community for exposing its corruption, and the leadership is replaced, what is the means by which those who exposed the corruption can be re-integrated, assuming they have trust in the new leadership? Currently there is no "re-evaluation" clause, which seems like an oversight.

I will leave this open for now to see if there is any more discussion.

**Comment by mjg59** [comment] 2017-02-16 16:50
The fcop allows communities to note behaviour outside the community and take precautions based on it. By blocking discussion of behaviour that occurs during active participation, you prevent other communities from being able to do the same.

But the second case is not as clear cut as you present it. If a victim is unsatisfied with the outcome of the resolution process, they have two choices: publicly denounce the decision and face banishment from the community, or put up with it anyway. The former may be associated with a significant professional cost, which may force them to accept the second even if they are unhappy with it. Prohibiting discussion of events under threat of banishment also makes it harder for a member to determine whether other community members feel the same way, making it easier for an abusive community to perpetuate itself.

**Comment by jdegoes** [comment] 2017-02-16 17:28
I'm still thinking through this but will leave this open for others to reply. A stated guiding principle of FCOP is to protect members against corruption of the community so this discussion is relevant.

But one quick clarification:

> Prohibiting discussion of events under threat of banishment also makes it harder for a member to determine whether other community members feel the same way, making it easier for an abusive community to perpetuate itself.

There is no prohibition on discussing an incident with other members of the same community. Mainly because all of them are bound by FCOP.

**Comment by mjg59** [comment] 2017-02-16 17:40
If a community's discussion forums are public, discussion of incidents with other members would be visible to non-members and therefore classifiable as shaming.

**Comment by ankushnarula** [comment] 2017-02-16 17:43
Perhaps the solution is to keep all relevant discussion before and after any arbitrated decisions isolated within a single forum and within it's own thread.  It's reasonable to assume that people will occasionally break decorum but most will adhere to such rules.

**Comment by jdegoes** [comment] 2017-02-16 17:46
> If a community's discussion forums are public, discussion of incidents with other members would be visible to non-members and therefore classifiable as shaming.

I think this is an oversight and can be fixed by clarifying that the scope is limited to private forums of communication. Needs some work, though, and is independent from your other points.

**Comment by jdegoes** [comment] 2017-02-16 23:20
> If a victim is unsatisfied with the outcome of the resolution process, they have two choices: publicly denounce the decision and face banishment from the community, or put up with it anyway. The former may be associated with a significant professional cost, which may force them to accept the second even if they are unhappy with it. 

So a different way to think about this is that they can be *somewhat* unhappy about the decision, but not *so unhappy* that they are unconcerned about future participation in the community. In other words, they find continued participation to be more valuable than vigilantism. 

If shaming has no cost for an aggrieved member, then it will be the default course of action, even in cases where a consequence has been imposed on the accused (as well as, of course, cases where an arbiter has rejected the accusation). Attaching a cost makes individuals think before acting.

In addition, entering into the community affords many protections, and it would be asymmetrical to take advantage of these protections, but at the same time, refuse to accept an arbiter-imposed consequence as sufficient. More symmetrical would be no protections, but freedom to shame publicly (which is not FCOP).

All said, I think this is the main point which needs addressing:

> If a community's discussion forums are public, discussion of incidents with other members would be visible to non-members and therefore classifiable as shaming.

And secondarily:

> Currently there is no "re-evaluation" clause, which seems like an oversight.

"Post-revolution re-evaluation".

**Comment by EvanBurchard** [comment] 2017-02-17 04:24
> If shaming has no cost for an aggrieved member, then it will be the default course of action, even in cases where a consequence has been imposed on the accused (as well as, of course, cases where an arbiter has rejected the accusation). Attaching a cost makes individuals think before acting.

Man..... seriously talk to women about this. JFC, you're not designing a board game.

**Comment by FaustDeGoethe** [comment] 2017-02-17 04:55
@EvanBurchard I'm a woman [not that it should matter] and I believe that public shaming and vigilanteism are serious problems. It's very easy to stir up an internet hate mob nowadays. Discouraging heat-of-the-moment public accusations could prevent lives from being ruined over some fleeting irritation or a simple misunderstanding.

**Comment by EvanBurchard** [comment] 2017-02-17 05:15
@FaustDeGoethe Oh it does matter. I'm glad you're involved.

I'm guessing you're talking about donglegate? That's not really my fight. I would have trouble hiring anyone involved with that without a conversation with them first. That's about as far as my opinion on that goes.

I'm just considering how many women I've seen clearly seated by the door at conferences. And how many times I've held my tongue on things when I've heard awful shit and felt like I wasn't "senior" enough to say anything (and I'm over it by this point). And all the times I've heard women say "this awful thing happened, but I'm not going to say anything, because [reason]." 

The thing is that [reason] could easily be the reputation of the conference, the strength of the CoC, or the attitudes of the organizers. 

I'm saying that right now, in this conversation, is where I'm feeling the strongest that the attitudes of the organizers are leading me to think that complaints would not be taken seriously, and that it's worth considering that.

People providing critiques en masse, especially if some of them are not being helpful, could, just maybe, mean that there *is* a problem, rather than it being a crazy "internet hate mob."

Serious Question:
If everyone who dissents is ignored and assumed to be of some crazy internet hate mob, then aren't you subject to a severe amount of confirmation and survivor bias?

**Comment by mjg59** [comment] 2017-02-17 05:28
@FaustDeGoethe If discouraging heat of the moment accusations also discourages considered allegations, it harms people who would otherwise be able to avoid being victims of the same individual.

If a member acts in a way that causes harm to another member (but doesn't reach the level of criminal behaviour), the aggrieved member cannot warn any other communities about the behaviour of the violator even if the community agrees that the behaviour was a violation. This protects a demonstrated violator at the expense of other communities.

But even if the community does not agree that a violation has occurred, other communities may still believe that the behaviour violates their own standards. The FCOP allows communities to take into account knowledge of behaviour that occurred in other communities, but prevents FCOP-bound communities from returning the favour. This asymmetry may encourage abusive individuals to congregate in FCOP communities, knowing that the probability of their abusive behaviour being publicly shared is reduced.

**Comment by FaustDeGoethe** [comment] 2017-02-17 06:00
@EvanBurchard 

> If everyone who dissents is ignored and assumed to be of some crazy internet hate mob, then aren't you subject to a severe amount of selection and survivor bias?

Up above John mentions a hypothetical situation where someone has an issue, takes it up with organizers, and isn't satisfied with the outcome -- i.e. someone got away with doing them harm. In that case he says:

>  I would encourage the aggrieved member to expose the corruption publicly.

This is about avoiding terrible situations like donglegate. Not about calling anyone who tweets a complain crazy, etc....

@mjg59 

> If a member acts in a way that causes harm to another member (but doesn't reach the level of criminal behaviour), the aggrieved member cannot warn any other communities about the behaviour of the violator even if the community agrees that the behaviour was a violation.

I'll agree that this could go too far. For instance, if someone makes a habit out of yelling "KILL FASCISTS!" during conference talks it would be good for other people to know so that they can act accordingly.

Maybe a more appropriate rule would be something along the lines of barring members from "publicly shaming" until after an event has ended. Or at least until after some adjudication has occurred.

**Comment by mjg59** [comment] 2017-02-17 06:23
@FaustDeGoethe It's worth mentioning that "Donglegate" was handled entirely in accordance with the conference policy that all attendees had agreed to. From the FCOP perspective, adjudication *had* occurred by the time any information was publicly posted.

**Comment by EvanBurchard** [comment] 2017-02-17 06:24
I'm not talking about people who tweet about a complaint at the time of the incident. I'm saying that some people are trying to offer other ideas here, and are getting shut down. I'm not a "member", or "aggrieved", or feeling that your group is "corrupt," just that you're not listening to outside perspectives. 

What I'm suggesting, generally, is that this process itself (of not listening to things that don't conform to the group's predetermined ideas of what a CoC should be) is actually evidence (for me) for my not trusting that I would be taken seriously if I were to "complain" for myself or on behalf of a friend (possibly through some block chain mechanism if you could possibly overengineer it further). 

I'm saying that your community seems to be creating safety for bad actors, and lots of restrictions and rules for the ones you call "victims."

Overall, I just feel like there are people who are actually trained in normative ethics in varying capacities and disciplines who could help with this. And seeing them try, and get shut down, is very discouraging.

**Comment by throwaway1973** [comment] 2017-02-17 10:30
I'd like to point out that as discussing rulings of a FCOP governed community is completely allowed, so long as personally identifiable details of the members in question are not included.  This seems like it supports the "somewhat unhappy about the decision" use case, since it allows for public discussion without requiring anyone to break the FCOP.

@EvanBurchard 
> I'm saying that your community seems to be creating safety for bad actors, and lots of restrictions and rules for the ones you call "victims."

This perspective makes sense to me, you're feeling protective of someone. That's a very good thing to motivate work on the FCOP. If it's not too forward, may I also suggest you also consider the importance of protecting these people from malicious accusations? Bad actors come in all types, unfortunately. I really like that the FCOP does not take either side by default, but instead waits for evidence.

**Comment by EvanBurchard** [comment] 2017-02-17 11:25
@throwaway1973

I don't really care if my dissent is sanctioned by a document on the internet made mostly by one person. There's a text box here and a green button. I'm using my real name and identity because a lot of people can't. I'm not speaking because it "allows" me to. I allow me to. The first issue I opened was a desire to be banned for "moralizing," because that's the dumbest thing I've ever heard, and along with "prying", it's an obvious signal to not question power structures, biases, and frankly, some things that some people actually need to know in order to feel safe. 

And nah man. I don't give a fuck about that side of it (the false accusations or whatever). I've been to enough conferences to know who has the power and who doesn't. It's not an equitable situation, and inventing a **hypothetical** counterweight, either in anecdotes, or in policy through a CoC is disingenuous, exclusive, and also narrow-minded.

"I could more likely be a hypothetical victim of being accused of harassment" is a bullshit stance to take: cowardly and selfish. Deciding *when* evidence is important enough to you is cherry-picking nonsense, and not every incident/resolution and outlook require it. Sometimes, there's just kindness and a demonstration of it. Look at the [geek feminism wiki](http://geekfeminism.wikia.com/wiki/Geek_Feminism_Wiki) and please tell me that there's a balance of incidents on the side that holds traditional power in tech. And please tell me that isn't the kind of evidence you're looking for. You already (maybe not intentionally?) ignored @mjg59's "evidence" on donglegate not fitting @FaustDeGoethe's narrative. If you rush to take a side against those incidents on the timeline, consider why, and consider how your support for FCOP plays into your biases.

Have I been annoyed in some contexts as a white male that I might not be if I wasn't? Maybe, but not often and it's pretty mild? Did I ever feel like I had to watch what I said around some people? Sure.

Does that warrant pretending people like me physically have to deal with anything close to the levels of harassment and just general shittiness others have to deal with for things they can't control? Hell no.

Your false dichotomy and FCOP's is a (I'm hoping unintentional) trojan horse for bad actors to feel real comfortable while the others are driven out or to never made to feel welcome in the first place. 

Yes, there's a big group that doesn't care or doesn't know. They aren't leaders, but a lot will be in 5 to 10 years.

In the mean time, what should I tell the junior programmers I mentor? FP is really cool, but communities are kinda full of racists and misogynists? I don't want to say that now or ever. There's already a bad scene in tech generally, and FP is worse generally.

Anyways, I don't want people to think this is a normal CoC or that bad actors aren't empowered by it. This is honestly like someone designing a board game with balances and factions and economies and complicated rules that doesn't do the 2 things it should:
1. no platform white supremacists (since that's been the biggest historical problem with lambdaconf)
2. make people feel safe and welcome (who wouldn't necessarily by default)

Other than that, there's no point to it. The power structure already exists. Codifying it in the way it's currently fashioned just makes it more severe.

Cue closing the thread for this conversation "going off the rails/topic" because a document on normative ethics can't encompass actual debate or dissenting viewpoints. I know I know. "Keep politics out of my everything I want to do and not think too hard about."

**Comment by FaustDeGoethe** [comment] 2017-02-17 12:31
> I'm saying that your community seems to be creating safety for bad actors, and lots of restrictions and rules for the ones you call "victims."

It's called rights of the accused.

The people [beating this man half to death](https://i.redditmedia.com/Tr5HvR52TusHBrKZlthFYvNrFUv8oxPSjJxSn0RhFu8.png?w=914&s=d8f0d97e4cea74aa230d1cf0a09bfdbb) think of themselves as victims because they don't like his opinions. Protecting some [arbitrarily defined] bad actors is important. FCOP is shooting for a peaceful environment with civil interactions.

**Comment by EvanBurchard** [comment] 2017-02-17 12:59
I didn't mean physical safety in the quote you pulled out. I meant comfort and lack of consequences. Obviously I'm not arguing for physical attacks on bad actors in your venue.

**Comment by FaustDeGoethe** [comment] 2017-02-17 13:18
> I'm using my real name and identity because a lot of people can't.

Using your real name to attack FCOP has a lot of upside. Many powerful people support "no platforming." Supporting it on the other hand, [not so much](https://twitter.com/ViceHN/status/823899251688214528).

> it's an obvious signal to not question power structures, biases, and frankly, some things that some people actually need to know in order to feel safe.

It's an obvious signal to act civil and professional towards people instead of browbeating them with some enlightened ideology. That goes for progressive liberals and evangelical Christians alike.

> And please tell me that isn't the kind of evidence you're looking for. You already (maybe not intentionally?) ignored @mjg59's "evidence" on donglegate not fitting @FaustDeGoethe's narrative.

I haven't responded to that yet, but it doesn't bust any narrative that I'm pushing. It actually just makes me think the original content of the COC was more on point than I'd imagined.

> no platform white supremacists (since that's been the biggest historical problem with lambdaconf)

Banning people accused of "white supremacy" [or witchcraft for that matter] from speaking about programming is not a moral imperative.

> make people feel safe and welcome (who wouldn't necessarily by default)

FCOP attempts to create an even playing field in light of the fact that power dynamics aren't stable.

I'm a woman in tech and, to be honest, that's the height of felicity. Almost everywhere I go people are falling over themselves to please me. Being a republican white male however seems like it would be hellish.

>  I know I know. "Keep politics out of my everything I want to do and not think too hard about."

It's perfectly reasonable for people to want to talk about technical subjects at tech conferences without getting into political arguments. Not everyone ascribes to the "personal is political" doctrine.

**Comment by mjg59** [comment] 2017-02-17 16:15
@throwaway1973 Shaming is defined as:

unauthorized, negative communication to non-members about a member's behavior inside the community, where negative is defined by the member on a case-by-case basis.

This doesn't appear to allow any discussion of incidents that relate to a member's behaviour, even if no PII is associated with that discussion. It's also explicitly stated that reported incidents and violations will remain confidential. I don't think it's obvious that discussing rulings is permitted.

**Comment by jdegoes** [comment] 2017-02-17 16:19
> It's perfectly reasonable for people to want to talk about technical subjects at tech conferences without getting into political arguments. Not everyone ascribes to the "personal is political" doctrine.

Indeed. FCOP is designed explicitly for this. I encourage people who cannot fathom participating in a community without bringing their religious, political, or moral debates into the community to look for other COCs. 

> What I'm suggesting, generally, is that this process itself (of not listening to things that don't conform to the group's predetermined ideas of what a CoC should be) is actually evidence (for me) for my not trusting that I would be taken seriously if I were to "complain" for myself or on behalf of a friend (possibly through some block chain mechanism if you could possibly overengineer it further).

You cannot persuade us to have different goals, because we created FCOP precisely because there was no pre-existing COC with our goals.

You can, however, attempt to persuade us that our goals (one of them being the provision of a physically and verbally safe environment during active participation) are not being met by the terms and conditions of FCOP. 

Do you see the difference? 

One of them is, "You're doing things all wrong," which amounts to, "I value different things, I want to force you to value the same things I value." That's not going to work. The other approach is, "You cannot obtain the goals [formed by your values] by the present formulation of FCOP." This is closer to the strategy that @mjg59 has been pursuing which has resulted in useful discussion.

> I'm saying that your community seems to be creating safety for bad actors, and lots of restrictions and rules for the ones you call "victims."

You are proceeding under the assumption that every accused person is a "bad actor", corrupt to the core, intent on spreading evil and destruction, and that every aggrieved person is a "good actor", saintly and righteous, incorruptible and unerring.

Do you understand the impetus behind the legal doctrine of innocent until proven guilty? Can you imagine how society would (not) function under the reverse, "guilty until proven innocent"? Do you know why the ACLU defends the right of literal (not "literal") Nazis to speak? 

Please go watch [Marlene Jaeckel](https://www.youtube.com/watch?v=iUcrreaSUEY), a woman technology veteran of 20 years, eager to mentor other women in tech, explain how she was banned from several Ruby communities for expressing mildly conservative (?) political opinions in an unrelated forum. 

If you want a COC that empowers such politically-motivated sabotage of people's professional careers, then FCOP is not the COC for you.

If you want a COC that empowers an irrational, rage-filled Twitter mob to ban anyone they deem "white supremacist", even if they are not a white supremacist, then FCOP is not the COC for you.

FCOP is designed to minimize abuses all around: abuses from leadership, abuses from social mobs, abuses from aggrieved, and abused from accused; and above all, to allow people who do not share the same politics, religions, or morals to participate in a shared community, physically and verbally safe, for the professional goals of the community.

**Comment by jdegoes** [comment] 2017-02-17 16:22
> This doesn't appear to allow any discussion of incidents that relate to a member's behaviour, even if no PII is associated with that discussion. It's also explicitly stated that reported incidents and violations will remain confidential. I don't think it's obvious that discussing rulings is permitted.

This needs clarification. The use of the words:

> a member's behavior

was intended to refer to a particular, identified member's behavior. This could be revised to:

> an identified member's behavior

or something similar.

**Comment by jdegoes** [comment] 2017-02-17 16:29
> But even if the community does not agree that a violation has occurred, other communities may still believe that the behaviour violates their own standards. The FCOP allows communities to take into account knowledge of behaviour that occurred in other communities, but prevents FCOP-bound communities from returning the favour. This asymmetry may encourage abusive individuals to congregate in FCOP communities, knowing that the probability of their abusive behaviour being publicly shared is reduced.

There was something in an earlier draft that attempted to address this, and I think the topic should be revisited. However, I would argue the following:

1. If the consequence imposed on an accused member is less severe than banning, it indicates the arbiter believes the accused will stop violating FCOP (perhaps because it was an unintentional violation, or done in brief moment of anger, etc.). 
2. If the consequence imposed on an accused member is banishment, it indicates the arbiter believes the accused incapable of upholding FCOP, or the offense severe or done in out of intentional malice.

It's the second case, I think, where broadcasting makes sense, because the FCOP community has essentially given up on the individual, which can be a useful warning sign to other communities.

**Comment by mjg59** [comment] 2017-02-17 17:04
@jdegoes If the consequences imposed on an accused member is less severe than banning, does it indicate that the arbiter believes the accused will stop violating FCOP in that community or does it indicate that the arbiter believes the accused will stop the violating behaviour under all circumstances? A violator may determine that the value of remaining in a community is greater than the value of continuing their violating behaviour within that community, especially if by doing so they ensure that there is no publicity surrounding their behaviour. They will then be free to do the same thing in other communities, who will be prevented from knowing that they have any history of violations due to the confidentiality and shaming provisions. 

Say we have FCOP communities 1 and 2, and members A, B.. A and B are members of both communities. In community 1, A sexually harasses B. B reports the incident, which is considered a violation. A apologises and is informed that if this behaviour is repeated in any way, A will be banished. In community 2, A sexually harasses B once more. If B informs community 2's leadership that A has done this before, B will be guilty of shaming under community 1's FCOP. As a result, the incident is treated as a one-off incident and A is forced to apologise and threatened with banishment if the behaviour is repeated.

An exception that allows B to report that A has engaged in this behaviour towards them before is insufficient. If community 2 also includes member C, and if A sexually harasses C rather than B, the confidentiality requirements may mean that B is in no position to be aware of the incident.

You've made it clear that a priority in writing the FCOP is avoiding cases where accusers who are bad actors are able to damage the careers of innocent individuals. However, in its current form the FCOP enables cases where abusers enjoy a greater degree of protection than would otherwise be the case. I don't believe you can achieve your goal without that being the case, so I think you need to be explicit about the fact that this is a risk associated with joining FCOP communities.

**Comment by jdegoes** [comment] 2017-02-17 17:37
@mjg59 This is definitely worth considering and discussing.

Note that in the situation you mention, the arbiter could, having more detailed knowledge of the nature of the accused member and the context surrounding the incident, decide to banish the accused for precisely this reason: because they suspect the accused is a bad actor, and wish to broadcast this fact to other communities (assuming such a broadcast clause is added). I know that if I were an arbiter, this is precisely what I would do (the decision tree for me: was this intentional, or unintentional; was this minor, or major; was this against the majority, or against a minority).

Possibly there is some middle ground in which FCOP leaders can share details about incidents with leaders of other FCOP communities, in confidence; or in which victims can share, in confidence, any personal details of the violator, on condition that leaders are then free to share their incident report with those same individuals if requested.

Further discussion welcome.

**Comment by jdegoes** [comment] 2017-02-17 17:49
> I'll agree that this could go too far. For instance, if someone makes a habit out of yelling "KILL FASCISTS!" during conference talks it would be good for other people to know so that they could act accordingly.

It sort of goes back to the above discussion: if the arbiter thinks the person is a good actor who unintentionally broke FCOP by shouting "KILL FASCISTS!" repeatedly, then OK, why broadcast that information? OTOH, if the arbiter thinks the person is a bad actor, and banishment is the result, then broadcasting that can be useful to other communities.

> Maybe a more appropriate rule would do something like bar members from "publicly shaming" until after an event has ended. Or at least until after some adjudication has occurred.

That's too broad, IMO. If a consequence has been imposed by the arbiter, then public shaming amounts to a separate consequence of unknown magnitude (maybe they lose their job, etc.).

I think public shaming and internal consequences don't mix. It's either public shaming as vigilantism (a method of imposing consequences on someone) and no internal consequences (because they are externally-imposed as a result of shaming), or no public shaming and internal consequences (AKA "accept the verdict of the court [unless the community is corrupt]").

Notwithstanding the points that @mjg59 raises above on bad actors, which need resolution.

**Comment by mjg59** [comment] 2017-02-17 18:00
@jdegoes Unless communities 1 and 2 share arbiters, the only way the arbiter would know about the context of prior incidents is if a community member has engaged in conduct that appears classifiable as shaming. So yes, some form of ability to communicate incidents is important. Let's walk through some examples of this:

1) Communities 1 and 2 have no members other than A in common, but have leadership that communicates. In this case, community 1's leadership could report the violation to community 2's leadership.
2) Communities 1 and 2 share both violator A and victim B, but their leadership is not in contact with each other. In this case, victim B could report the violation to community 2's leadership
3) Communities 1 and 2 have no members other than A in common, and their leadership is not in contact with each other. In this case, should victim B be able to report the violation to community 2's leadership?
4) Communities 1 and 2 have no members other than A in common, and their leadership is not in contact with each other. In addition, community 2 is not an FCOP-bound community. In this case, should victim B be able to report the violation to community 2's leadership?

**Comment by EvanBurchard** [comment] 2017-02-17 19:50
@jdegoes Watched Marlene Jaeckel. At this point, it's clear what the point of this CoC is. I guess I'm unclear why this is a public project or a project at all, and that won't be clarified by any further explanation. I don't have to understand or agree and that's fine. I'm glad I have this context for the future.

**Comment by jdegoes** [comment] 2017-02-18 22:50
@mjg59 @ankushnarula @FaustDeGoethe 

My tentative proposal is as follows:

1. Add a broadcast clause for banishment. This allows arbiters to decide someone is a bad actor and banish someone specifically to broadcast the incident publicly. It's consistent with banishment being the "we're giving up on this person" option, and provides useful information to other communities (so and so was banished for a violation of FCOP), of the same type that FCOP benefits from. 
2. Allow victims to confidentially share any and all details (including PII) about incidents (whether or not deemed violations), on condition that the community leaders are then free to confidentially share an official incident report to those same people if they deem it to be useful. This allows victims to proactively communicate information to other communities. It can also be seen as a way to protect victims from powerful communities that serve such such an important role for a victim, that the victim would rather not face banishment by exposing the corruption of the community (example: an open source project that the victim started but no longer controls).
3. Make it clear that privately or publicly communicating generic (non-identifiable) information about incidents is perfectly acceptable.

**Comment by mjg59** [comment] 2017-02-19 06:39
@jdegoes For point 2, can you define share? Also, is this transitive - if a victim shares information about an incident to another community member, can that community member share the information further? If a third party witnesses an incident, are they able to share that information even if the victim is not inclined to? Am I correct in thinking that since the definition of incident doesn't require that it be reported, this applies regardless of whether an incident report is created?

**Comment by jdegoes** [comment] 2017-02-19 17:28
@mjg59 I would define it as _communication_, and make it non-transitive; i.e. it can be confidentially communicated to others only on condition those others not further disseminate the information.

> If a third party witnesses an incident, are they able to share that information even if the victim is not inclined to? 

Currently, no. It protects against abuse: an aggrieved member may not wish details of an incident shared (indeed, may not even consider it noteworthy—consider two friends engaging in good-natured ribbing that, on face value, might violate the denigration or moralizing clauses).

> Am I correct in thinking that since the definition of incident doesn't require that it be reported, this applies regardless of whether an incident report is created?

I'd have a preference for allowing it only for reported incidents, on grounds this gives the community a chance to deal with the incident before aggrieved members start sharing. The flip side is that reporting an incident to a corrupt community might benefit from protections for the reporter (although FCOP provides no means to impose a consequence on reporters, its scope is not comprehensive with respect to the roles of members in the community).

**Comment by mjg59** [comment] 2017-02-19 17:49
@jdegoes If information about an incident is communicated to a third party outside the community who then disseminates that information further, what are the consequences and who do they apply to?

> Currently, no. It protects against abuse: an aggrieved member may not wish details of an incident shared (indeed, may not even consider it noteworthy—consider two friends engaging in good-natured ribbing that, on face value, might violate the denigration or moralizing clauses).

It also protects abuse: if long-term member A denigrates new member B and is witnessed by long-term member C, B may feel that reporting the incident will harm their standing in the community more than the denigration harmed them.

> I'd have a preference for allowing it only for reported incidents, on grounds this gives the community a chance to deal with the incident before aggrieved members start sharing.

While third parties are unable to report incidents, I think this is a problem.

**Comment by jdegoes** [comment] 2017-02-19 18:21
> If information about an incident is communicated to a third party outside the community who then disseminates that information further, what are the consequences and who do they apply to?

Consequences can apply only to members, so they would apply to the aggrieved, which would incentivize the aggrieved to share only with trusted sources. That said, an arbiter would have to be involved to impose any consequence on a breach of privacy, and I'd expect in a non-corrupt community the arbiter would take the specifics of the situation into account.

> It also protects abuse: if long-term member A denigrates new member B and is witnessed by long-term member C, B may feel that reporting the incident will harm their standing in the community more than the denigration harmed them.

This is in the event that the community is corrupt, correct? In a non-corrupt community, reporting an incident is confidential and can have no consequences.

If we assume the community is corrupt but ongoing participation for the aggrieved still has value sufficient to disincentivize exposure of the corruption, then I would encourage the aggrieved to break FCOP by sharing information with trusted third-parties, who can provide a support network and possibly help implement strategies to expose the corruption in a way that does not reveal identities.

Note that if you assume corruption you cannot assume the community will keep any part of FCOP, so it's not possible to "force" a corrupt community into certain behaviors.

> While third parties are unable to report incidents, I think this is a problem.

If third-parties are able to report incidents, how does this protect against corrupt communities? In a corrupt community, the third-parties themselves would be subject to "corrupt" consequences for reporting an incident. On the other hand, if the community is not corrupt, then whether the incident is reported by the aggrieved or by a third-party, it has no consequences and is kept confidential.

**Comment by mjg59** [comment] 2017-02-19 18:54
> Consequences can apply only to members, so they would apply to the aggrieved, which would incentivize the aggrieved to share only with trusted sources. 

The goal here was to ensure that knowledge of incidents can reach other communities in order for them to be able to pre-emptively block members that they believe will act in ways contrary to their community goals. If this requires a member to personally communicate information about the violator to every community that the violator may seek to join, this becomes impractical, especially if the member faces consequences in the event of a single one of those communities passing information along.

>  In a non-corrupt community, reporting an incident is confidential and can have no consequences.

This seems unlikely. If any action is taken, it's going to be clear to member A that it's in relation to member B. Member A is then free to apply harsher judgements to contributions from member B, making it more difficult for member B to be involved in the community. There are multiple other ways that member A can enact retribution without clearly violating the FCOP.

> If third-parties are able to report incidents, how does this protect against corrupt communities?

It doesn't, and it can't. But if third parties can report incidents, it's not automatically clear to member A that member B reported the incident, and so there's less incentive to enact retribution against them.

**Comment by jdegoes** [comment] 2017-02-19 19:14
> The goal here was to ensure that knowledge of incidents can reach other communities in order for them to be able to pre-emptively block members that they believe will act in ways contrary to their community goals. 

This can be abused, too, from a malicious aggrieved member who wishes to prevent disliked or hated enemies from participating in other communities. This is why an incident report is so important, because it provides a chance for other communities to hear the other side of the story, including eyewitness reports, and so on.

> If this requires a member to personally communicate information about the violator to every community that the violator may seek to join, this becomes impractical, especially if the member faces consequences in the event of a single one of those communities passing information along.

I'd think the aggrieved member would communicate only to those communities the aggrieved member is considering to join or already participates in, and in which the accused member is also a member.

> It doesn't, and it can't. But if third parties can report incidents, it's not automatically clear to member A that member B reported the incident, and so there's less incentive to enact retribution against them.

In this example, if witness member C communicates information about an incident to the community leaders, then from the point of view of accused member A, this is identical to the situation in which aggrieved member C communicates information about an incident. The fact that an obscure byline in FCOP might allow for the possibility that witnesses communicated the information seems insufficient disincentive for accused member A to exact no payback on aggrieved member C. But I could be wrong about this prediction.

I also like the ability for witnesses to report violations, if potential for abuse can be minimized. Unfortunately, I think what would prevent abuse is to require a third-party report be authenticated by the aggrieved member ("Yes, that happened, and yes, it's not OK with me,"), yet that's the very same thing that would close the loop and enable accused member A to know that aggrieved member C was involved in the process, even if only indirectly.

**Comment by mjg59** [comment] 2017-02-19 19:27
> I'd think the aggrieved member would communicate only to those communities the aggrieved member is considering to join or already participates in

Why? If the aggrieved member has friends in other communities, they'd obviously have an incentive to protect those friends. If they care about the overall state of the larger community, they'd have an incentive to protect communities that they have no association with whatsoever.

> In this example, if witness member C communicates information about an incident to the community leaders, then from the point of view of accused member A, this is identical to the situation in which aggrieved member C communicates information about an incident. 

I'm assuming that you meant "Aggrieved member B". It's not identical - if third parties can report incidents, member B can plausibly deny reporting the incident and member A has less incentive to react to them.

> it's not OK with me

This supports that the "No victimless crimes" criterion is a problem. Requiring the victim to make a judgement call about whether something was a violation or not allows member A to influence their decision.

**Comment by jdegoes** [comment] 2017-02-19 22:24
> Why? If the aggrieved member has friends in other communities, they'd obviously have an incentive to protect those friends. If they care about the overall state of the larger community, they'd have an incentive to protect communities that they have no association with whatsoever.

I view some sort of cost as desirable, because it acts as a disincentive for abuse by the aggrieved. It's easy to think of the aggrieved as being a victim, but remember that is not necessarily the case; in some cases, it will be the aggrieved who is an abuser, and a central goal of FCOP is to protect against all types of abuses, not just one type.

For example, let's say I get into a Twitter fight with someone. I don't like them. I want to hurt them. So I publicly broadcast, "So and so harassed me in the community." Maybe I made it up, or maybe it's an gross exaggeration of the truth, or maybe it's merely from my point of view but other independent witnesses would not agree with my story.

In such cases, if this broadcasting has no cost, there is no disincentive, and therefore it will be abused, with potentially great and uncontrollable costs to the abused. A cost-based disincentive will decrease the number of times this happens.

I think the most useful direction is figuring out what costs minimizes in-balances / potential for abuse under the assumption that any party is likely to be an abuser.

> I'm assuming that you meant "Aggrieved member B". It's not identical - if third parties can report incidents, member B can plausibly deny reporting the incident and member A has less incentive to react to them.

I agree there is a difference here. Plausible deniability allows aggrieved member B to say, "It wasn't me, I swear!" It occurs to me that making retaliation for an incident report a clear violation of FCOP might also be useful.

> This supports that the "No victimless crimes" criterion is a problem. Requiring the victim to make a judgement call about whether something was a violation or not allows member A to influence their decision.

As per #55, the clause will be removed, or rather, rewritten, but I'm not sure if the alternate form has any less susceptibility to this issue. FCOP is by some standards somewhat draconian, in the sense that it is expected conversations and interactions will stay professional; numerous things could be considered violations, from a couple holding hands to a group discussing the morality of data mining. Granting that none of these need be violations in a group of consenting adults is useful for (a) accommodating what some people will do anyway, (b) treating adults like adults, (c) not supporting "victimless crimes", and (d) minimizing busywork for community leaders.

All things being equal, I would not want it to be possible for member A to influence the decision on whether or not to report something as an incident. Perhaps there is some way to achieve or at least incentivize this without tampering with the successor to "no victimless violations", such as the previously suggested "no retaliation" clause, which at least would make sure that any kind of retaliation is a bannable offense (granted, this only helps with non-corrupt communities and only in cases where retaliation is measurable).

**Comment by mjg59** [comment] 2017-02-19 22:44
> a central goal of FCOP is to protect against all types of abuses, not just one type.

It's impossible to protect against all types of abuses. By protecting against certain types of abuse, you're making it easier to perform others. Do you have objective evidence that the abuse you're attempting to prevent in this case is more common than the abuse you're enabling in the process?

**Comment by jdegoes** [comment] 2017-02-19 22:52
> It's impossible to protect against all types of abuses. By protecting against certain types of abuse, you're making it easier to perform others. Do you have objective evidence that the abuse you're attempting to prevent in this case is more common than the abuse you're enabling in the process?

I can't usefully estimate likelihood because I only see what I find out about through direct reports or indirect reports. But I can attest to the fact that organizers see all kinds of things that never make it to the surface, and I have seen abuses of aggrieved against their enemies (in situations far stranger than you might imagine).

The abuse scenario that you are concerned about is an incident in which an aggrieved member is afraid to report on due to fear of retaliation on the part of the accused; but in which the aggrieved member wishes to disseminate information on the incident.

I think (a) adding No Retaliation, and (b) providing a way to confidentially disseminate information (albeit at cost) addresses both in a way that provides some disincentive against abusers. But possibly there are solutions which further reduce the potential for abuse.

**Comment by jdegoes** [comment] 2017-02-20 16:40
I think the solution to the above issue is actually quite simple: allow third-party reports at the discretion of the community leaders. This allows leaders to limit abuse and provides plausible deniability for aggrieved members.

**Comment by mjg59** [comment] 2017-02-20 21:36
@jdegoes How does this differ from "Allow third-party reports under all circumstances and take the third-party nature of the report into consideration while investigating"?

**Comment by jdegoes** [comment] 2017-02-20 21:51
@mjg59 The difference is the "right to dismiss" an incident without investigation, essentially mirror to the judicial system's right to dismiss a case without hearing it (by prosecutor or court). One would impose a guaranteed cost of investigation on every report by a third-party, while the other provides the ability to investigate a third-party report but does not require it.

**Closed** 2017-02-28 05:01 UTC
